# Workaround for the issue found in the stable image promoted on Dec 1, 2016.
# See https://github.com/travis-ci/travis-ci/issues/6928#issuecomment-264227708
group: deprecated
sudo: required
#dist: precise

notifications:
  email: false
language: c #NOTE: this will set CC=gcc which might cause trouble
before_script:
  - WGET="travis_retry wget --continue --tries=20 --waitretry=10 --retry-connrefused --no-dns-cache --timeout 300"
  - sudo apt-get -qq update

  ## Support building a binary that is identical to the CI
  - echo -n "Contiki will be compiled with RELSTR=" ; git --git-dir .git describe --tags --always

  ## Install doxygen
  - if [ ${BUILD_CATEGORY:-0} = doxygen ] ; then
    sudo add-apt-repository ppa:libreoffice/ppa -y && sudo apt-get -qq update &&
    sudo apt-get --no-install-suggests --no-install-recommends -qq install doxygen  &&
    doxygen --version ;
    fi

  ## Install msp430 toolchain
  - sudo apt-get -qq install lib32z1
  - $WGET http://simonduq.github.io/resources/mspgcc-4.7.2-compiled.tar.bz2 &&
    tar xjf mspgcc*.tar.bz2 -C /tmp/ &&
    sudo cp -f -r /tmp/msp430/* /usr/local/ &&
    rm -rf /tmp/msp430 mspgcc*.tar.bz2 &&
    msp430-gcc --version

  ## Install 32-bit compatibility libraries
#  - sudo apt-get -qq install libc6:i386 libgcc1:i386 gcc-4.6-base:i386
#    libstdc++5:i386 libstdc++6:i386

  ## IMPORTANT: The commands here have to end with `|| true`,
  ## because it would make the test fail if BUILD_TYPE test fails

script:
  - cd apps/ecc/tester
  - make TARGET=sky testCPABE
#  - cd ../linux
#  - make
#  - ./testCPABE

after_script:


