//
// Created by Daniel on 22.06.2020.
//

#ifndef CONTIKI_CPABE_NN2MOCK_H
#define CONTIKI_CPABE_NN2MOCK_H

#include <fff.h>
#include "NN2.h"

DEFINE_FFF_GLOBALS;

FAKE_VOID_FUNC(NN2ModMult, NN2_NUMBER*, NN2_NUMBER*, NN2_NUMBER*, NN_DIGIT*, NN_UINT);
FAKE_VOID_FUNC(NN2ModSqr, NN2_NUMBER *, NN2_NUMBER *, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NN2ModExp, NN2_NUMBER *, NN2_NUMBER *, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NN2ModInv, NN2_NUMBER *,NN2_NUMBER *,NN_DIGIT *,NN_UINT);
FAKE_VOID_FUNC(NN2Assign, NN2_NUMBER *,NN2_NUMBER *,NN_UINT);
FAKE_VOID_FUNC(NN2AssignNN, NN2_NUMBER *,NN_DIGIT *,NN_UINT);
FAKE_VALUE_FUNC(uint8_t, NN2LucExp, NN2_NUMBER *,NN2_NUMBER *, NN_DIGIT *,NN_DIGIT *,NN_DIGIT *,NN_UINT);
FAKE_VOID_FUNC(NN2ModRandom, NN2_NUMBER *, NN_DIGIT *, NN_UINT);


#endif // CONTIKI_CPABE_NN2MOCK_H
