//
// Created by Daniel on 22.06.2020.
//

#ifndef CONTIKI_CPABE_NN2MOCK_H
#define CONTIKI_CPABE_NN2MOCK_H

#include <fff.h>
#include "NN.h"

DEFINE_FFF_GLOBALS;

FAKE_VOID_FUNC(NNDecode, NN_DIGIT *, NN_UINT, unsigned char *, NN_UINT);
FAKE_VOID_FUNC(NNEncode, unsigned char *, NN_UINT, NN_DIGIT *, NN_UINT);

FAKE_VOID_FUNC(NNAssign, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNAssignDigit, NN_DIGIT *, NN_DIGIT, NN_UINT);
FAKE_VOID_FUNC(NNAssignZero, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNAssign2Exp, NN_DIGIT *, NN_UINT2, NN_UINT);

FAKE_VALUE_FUNC(NN_DIGIT, NNAdd, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VALUE_FUNC(NN_DIGIT, NNSub, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNMult, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNDiv, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT, NN_DIGIT *, NN_UINT);
FAKE_VALUE_FUNC(NN_DIGIT, NNLShift, NN_DIGIT *, NN_DIGIT *, NN_UINT, NN_UINT);
FAKE_VALUE_FUNC(NN_DIGIT, NNRShift, NN_DIGIT *, NN_DIGIT *, NN_UINT, NN_UINT);
FAKE_VALUE_FUNC(NN_DIGIT, NNAddDigitMult, NN_DIGIT *, NN_DIGIT *, NN_DIGIT, NN_DIGIT *, NN_UINT);

FAKE_VOID_FUNC(NNMod, NN_DIGIT *, NN_DIGIT *, NN_UINT, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNModBarrettInit, NN_DIGIT *, NN_UINT, Barrett *);
FAKE_VOID_FUNC(NNBarrettSetBuf, Barrett *);
FAKE_VOID_FUNC(NNModBarrett, NN_DIGIT *, NN_DIGIT *, NN_UINT, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNModSmall, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNModAdd, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNModSub, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNModNeg, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNModMult, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNModDiv, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNModMultOpt, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNModDivOpt, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNModSqr, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNModSqrOpt, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNModExp, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNModInv, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNGcd, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VALUE_FUNC(int, NNModSqrRootOpt, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT, NN_DIGIT *);
//FAKE_VOID_FUNC(ModDivOpt, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, );

FAKE_VALUE_FUNC(int, NNCmp, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VALUE_FUNC(int, NNZero, NN_DIGIT *, NN_UINT);
FAKE_VALUE_FUNC(int, NNOne, NN_DIGIT *, NN_UINT);
FAKE_VALUE_FUNC(unsigned int, NNBits, NN_DIGIT *, NN_UINT);
FAKE_VALUE_FUNC(NN_DIGIT, NNTestBit, NN_DIGIT *, int16_t);
FAKE_VALUE_FUNC(unsigned int, NNDigits, NN_DIGIT *, NN_UINT);
FAKE_VALUE_FUNC(uint8_t, NNEqual, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VALUE_FUNC(uint8_t, NNEven, NN_DIGIT *, NN_UINT);
FAKE_VALUE_FUNC(uint8_t, NNLucExp, NN_DIGIT *,NN_DIGIT *, NN_DIGIT *,NN_DIGIT *,NN_DIGIT *,NN_UINT);

FAKE_VOID_FUNC(NNModRandom, NN_DIGIT *, NN_DIGIT *, NN_UINT);
FAKE_VOID_FUNC(NNAssignOne, NN_DIGIT *, NN_UINT);
//FAKE_VOID_FUNC(NNModMultVar, NN_DIGIT *, NN_DIGIT *, NN_DIGIT *, NN_UINT, NN_DIGIT *, NN_UINT);


#endif // CONTIKI_CPABE_NN2MOCK_H
